DOMAIN = "inim_prime"

CONF_HOST = "host"
CONF_API_KEY = "api_key"
CONF_USE_HTTPS = "use_https"
CONF_SERIAL_NUMBER = "serial_number"
CONF_PANEL_LOG_EVENTS_FETCH_LIMIT = "panel_log_events_fetch_limit"
CONF_PANEL_LOG_EVENTS_FETCH_LIMIT_DEFAULT = 40
CONF_PANEL_LOG_EVENTS_FETCH_LIMIT_TRIGGER = 5
CONF_PANEL_LOG_EVENTS_FETCH_LIMIT_MIN = 10
CONF_PANEL_LOG_EVENTS_FETCH_LIMIT_MAX = 100

CONF_SCAN_INTERVAL = 30

STORAGE_KEY_LAST_PANEL_EVENT_LOGS = "last_panel_event_logs"

INIM_PRIME_DEVICE_MANUFACTURER = "Inim"
INIM_PRIME_MODEL_ZONE = "Prime Zone"