DOMAIN = "inim_prime"

CONF_HOST = "host"
CONF_API_KEY = "api_key"
CONF_USE_HTTPS = "use_https"
CONF_SERIAL_NUMBER = "serial_number"
CONF_PANEL_LOG_EVENTS_FETCH_LIMIT = "panel_log_events_fetch_limit"
CONF_PANEL_LOG_EVENTS_FETCH_LIMIT_DEFAULT = 40
CONF_PANEL_LOG_EVENTS_FETCH_LIMIT_TRIGGER = 3
CONF_PANEL_LOG_EVENTS_FETCH_LIMIT_MIN = 10
CONF_PANEL_LOG_EVENTS_FETCH_LIMIT_MAX = 100

PANEL_LOG_EVENTS_COORDINATOR = "panel_log_events_coordinator"

CONF_MAIN_SCAN_INTERVAL = "main_scan_interval"
CONF_PANEL_LOG_EVENTS_SCAN_INTERVAL = "log_scan_interval"

CONF_MAIN_SCAN_INTERVAL_DEFAULT = 10
CONF_PANEL_LOG_EVENTS_SCAN_INTERVAL_DEFAULT = 20

CONF_SCAN_INTERVAL_MIN = 1
CONF_SCAN_INTERVAL_MAX = 300

STORAGE_KEY_LAST_PANEL_EVENT_LOGS = "last_panel_event_logs"

INIM_PRIME_DEVICE_MANUFACTURER = "Inim"
INIM_PRIME_MODEL_ZONE = "Prime Zone"
